# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb501f51b6e590a8ed03e73a64aa5c0bf386f946a75e865fa602a432e79fd959934412fea634c340555fe3e7f9939038fe225954324c494197a857b164a07642

test:
  secret_key_base: 0be640779ba545ca986ebbbd7998075ec7683e38f188840f8704e22092d1a649a60027d28b7bd01caaeea07c5434816d7eb5311b73f498254bb3bff0dbe31647

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
